import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import * as adapterFilesystem from "@contentmd/adapter-filesystem";

const root = fileURLToPath(
  new URL("../../../fixtures/synthetic-mixed-stack/", import.meta.url),
);
const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) =>
    rm(directory, { recursive: true, force: true })
  ));
});

describe("repository inventory", () => {
  it("inventories safe mixed-stack artifacts without exposing private or generated bytes", async () => {
    expect(typeof adapterFilesystem.inventoryRepository).toBe("function");

    const result = await adapterFilesystem.inventoryRepository({ project_root: root });

    expect(result.artifacts.map((item) => item.relative_path)).toEqual(expect.arrayContaining([
      "pyproject.toml",
      "studio/package.json",
      "studio/app/page.tsx",
      "api/main.py",
      "docs/context/PRODUCT-IDENTITY.md",
    ]));
    expect(result.exclusions).toEqual(expect.arrayContaining([
      expect.objectContaining({ relative_path: ".env", reason: "credential_or_environment" }),
      expect.objectContaining({ relative_path: "data", reason: "private_or_bulk_data" }),
      expect.objectContaining({ relative_path: "outputs", reason: "generated_output" }),
    ]));
    expect(JSON.stringify(result)).not.toContain("SECRET_CANARY");
    expect(JSON.stringify(result)).not.toContain("PRIVATE_DATA_CANARY");
    expect(JSON.stringify(result)).not.toContain("GENERATED_OUTPUT_CANARY");
    expect(result.inventory_digest).toMatch(/^[a-f0-9]{64}$/u);
  });

  it("records an escaping file symlink without reading its target", async () => {
    const repository = await mkdtemp(join(tmpdir(), "contentmd-inventory-root-"));
    const outside = await mkdtemp(join(tmpdir(), "contentmd-inventory-outside-"));
    temporaryDirectories.push(repository, outside);
    await writeFile(join(repository, "README.md"), "# Safe repository\n", "utf8");
    await writeFile(join(outside, "secret.md"), "SYMLINK_SECRET_CANARY\n", "utf8");
    await symlink(join(outside, "secret.md"), join(repository, "linked-secret.md"));

    const result = await adapterFilesystem.inventoryRepository({ project_root: repository });

    expect(result.exclusions).toContainEqual({
      relative_path: "linked-secret.md",
      reason: "outside_project_root",
    });
    expect(JSON.stringify(result)).not.toContain("SYMLINK_SECRET_CANARY");
  });

  it("records a dangling symlink without aborting repository discovery", async () => {
    const repository = await mkdtemp(join(tmpdir(), "contentmd-inventory-dangling-"));
    temporaryDirectories.push(repository);
    await writeFile(join(repository, "README.md"), "# Safe repository\n", "utf8");
    await symlink(join(repository, "missing-directory"), join(repository, "unavailable-content"));

    const result = await adapterFilesystem.inventoryRepository({ project_root: repository });

    expect(result.exclusions).toContainEqual({
      relative_path: "unavailable-content",
      reason: "unavailable_symlink",
    });
    expect(result.coverage.failed).toBe(0);
    expect(result.artifacts.map((artifact) => artifact.relative_path)).toEqual(["README.md"]);
  });

  it("excludes temporary files before their bytes enter the inventory", async () => {
    const repository = await mkdtemp(join(tmpdir(), "contentmd-inventory-temporary-"));
    temporaryDirectories.push(repository);
    await writeFile(join(repository, "README.md"), "# Safe repository\n", "utf8");
    await writeFile(join(repository, "scratch.tmp"), "TEMPORARY_FILE_CANARY\n", "utf8");

    const result = await adapterFilesystem.inventoryRepository({ project_root: repository });

    expect(result.exclusions).toContainEqual({
      relative_path: "scratch.tmp",
      reason: "dependency_or_cache",
    });
    expect(JSON.stringify(result)).not.toContain("TEMPORARY_FILE_CANARY");
  });

  it("classifies binary and oversize files without retaining their bytes", async () => {
    const repository = await mkdtemp(join(tmpdir(), "contentmd-inventory-bounds-"));
    temporaryDirectories.push(repository);
    await writeFile(join(repository, "binary.dat"), Buffer.from([0, 1, 2, 3]));
    await writeFile(join(repository, "oversize.md"), Buffer.alloc((2 * 1024 * 1024) + 1, 65));

    const result = await adapterFilesystem.inventoryRepository({ project_root: repository });

    expect(result.exclusions).toEqual(expect.arrayContaining([
      { relative_path: "binary.dat", reason: "binary_or_oversize" },
      { relative_path: "oversize.md", reason: "binary_or_oversize" },
    ]));
    expect(result.coverage.unsupported).toBe(2);
    expect(result.bytes_read).toBe(4);
    expect(result.resource_ceiling).toEqual({ max_file_bytes: 2 * 1024 * 1024 });
  });

  it("excludes nested VCS metadata while retaining a malformed manifest as inert text", async () => {
    const repository = await mkdtemp(join(tmpdir(), "contentmd-inventory-vcs-"));
    temporaryDirectories.push(repository);
    await mkdir(join(repository, "nested", ".git"), { recursive: true });
    await writeFile(join(repository, "nested", ".git", "config"), "VCS_METADATA_CANARY\n", "utf8");
    await writeFile(join(repository, "pyproject.toml"), "[project\nmalformed = true\n", "utf8");

    const first = await adapterFilesystem.inventoryRepository({ project_root: repository });
    const second = await adapterFilesystem.inventoryRepository({ project_root: repository });

    expect(first.exclusions).toContainEqual({
      relative_path: "nested/.git",
      reason: "dependency_or_cache",
    });
    expect(first.artifacts.map((artifact) => artifact.relative_path)).toContain("pyproject.toml");
    expect(JSON.stringify(first)).not.toContain("VCS_METADATA_CANARY");
    expect(second).toEqual(first);
  });

  it("excludes local test cassettes before parser federation", async () => {
    const repository = await mkdtemp(join(tmpdir(), "contentmd-inventory-cassette-"));
    temporaryDirectories.push(repository);
    await mkdir(join(repository, ".contentmd-test"));
    await writeFile(join(repository, ".contentmd-test", "responses.jsonl"), "CASSETTE_PRIVATE_CANARY\n", "utf8");

    const result = await adapterFilesystem.inventoryRepository({ project_root: repository });

    expect(result.exclusions).toContainEqual({
      relative_path: ".contentmd-test",
      reason: "dependency_or_cache",
    });
    expect(JSON.stringify(result)).not.toContain("CASSETTE_PRIVATE_CANARY");
  });

  it("excludes nested worktrees and repository-corpus mirrors before traversal", async () => {
    const repository = await mkdtemp(join(tmpdir(), "contentmd-inventory-mirrors-"));
    temporaryDirectories.push(repository);
    await mkdir(join(repository, ".worktrees", "feature"), { recursive: true });
    await mkdir(join(repository, "content-repos", "mirrored-product"), { recursive: true });
    await writeFile(join(repository, ".worktrees", "feature", "private.md"), "WORKTREE_MIRROR_CANARY\n", "utf8");
    await writeFile(join(repository, "content-repos", "mirrored-product", "private.md"), "CORPUS_MIRROR_CANARY\n", "utf8");
    await writeFile(join(repository, "README.md"), "# Safe repository\n", "utf8");

    const result = await adapterFilesystem.inventoryRepository({ project_root: repository });

    expect(result.exclusions).toEqual(expect.arrayContaining([
      { relative_path: ".worktrees", reason: "dependency_or_cache" },
      { relative_path: "content-repos", reason: "private_or_bulk_data" },
    ]));
    expect(JSON.stringify(result)).not.toContain("WORKTREE_MIRROR_CANARY");
    expect(JSON.stringify(result)).not.toContain("CORPUS_MIRROR_CANARY");
  });
});
