export const PACKAGE_ID = "@contentmd/learning" as const;

export * from "./candidate.js";
export * from "./feedback.js";
export * from "./qualification.js";
export * from "./eligibility.js";
export * from "./preference.js";
export * from "./unicode-normalization.js";
export * from "./leakage.js";
export * from "./dataset.js";
export { retrieveApprovedPatterns, verifyRetrievalSnapshot } from "./retrieval.js";
export type {
  ApprovedRetrievalCandidate,
  QuarantinedRetrievalCandidate,
  RetrievalDispositionEvidence,
  RetrievalExclusion,
  RetrievalExclusionReason,
  RetrievalHit,
  RetrievalInput,
  RetrievalProjection,
  RetrievalProjectionEvidence,
  RetrievalQuery,
  RetrievalScore,
  RetrievalSnapshot,
  RetrievalTransferCondition,
  Task4AllowedSourceClass,
  Task4ContentPatternPayload,
  Task4ContentPatternRecord,
  Task4DependencyManifest,
  Task4DependencyManifestEntry,
  Task4PatternContext,
  Task4ProducerArtifactWitness,
  Task4ProvenanceRef,
  Task4QuarantinedSourceClass,
  Task4RecordMode,
  Task4Relationship,
  Task4UnicodeRuntime,
  VerifyRetrievalSnapshotInput,
} from "./retrieval.js";
export { createFeatureProfile, vectorizeCandidate } from "./features.js";
export type {
  CandidateEligibilityGate,
  CandidateFeatureExclusion,
  CandidateFeatureResult,
  CandidateFeatureVector,
  CandidateRule,
  CandidateRuleBase,
  CandidateRuleEvaluation,
  CandidateRuleFinding,
  CandidateRuleSet,
  CandidateVectorizationInput,
  CreateFeatureProfileInput,
  FeatureArtifactBinding,
  FeatureContextBinding,
  FeatureMaterial,
  FeatureUniverseManifest,
  ReferenceFeatureMaterialKind,
  ScopeMaterial,
  TextFeatureMaterialKind,
} from "./features.js";
export {
  compareDeterministicBaseline,
  createDeterministicBaseline,
  orderBaselineCandidates,
  scoreDeterministicBaseline,
} from "./baseline.js";
export type {
  BaselineCandidateScore,
  BaselineComponent,
  BaselineOrderedCandidate,
  BaselineOrderingInput,
  BaselinePairInput,
  BaselinePairResult,
  BaselineScoreInput,
  CreateBaselineInput,
  DeterministicBaseline,
} from "./baseline.js";
export {
  binary64FromHex,
  binary64ToHex,
  kahanSum,
  stableSigmoid,
  stableSoftplus,
} from "./numeric.js";
export type {
  Binary64Hex,
  PairwiseRankingErrorCode,
  PairwiseRankingErrorShape,
} from "./numeric.js";
export {
  admitPairwiseRuntime,
  trainPairwiseLogistic,
  verifyLearningDatasetForTraining,
  verifyPairwiseCandidate,
  verifyPairwiseCodeManifest,
  verifyPairwiseFeatureMatrix,
  verifyRankingModel,
} from "./pairwise-logistic.js";
export type {
  CodeManifestEntry,
  LearningDatasetTrainingReplay,
  ModelTrainingStatisticsPayload,
  ModelTrainingStatisticsRecord,
  PairwiseCandidateVectorReplay,
  PairwiseCodeManifest,
  PairwiseFeatureMatrixReplay,
  PairwiseFeatureProfileReplay,
  PairwiseRuntimeProfile,
  PairwiseTrainingRequest,
  PairwiseTrainingResult,
  RankingModelDependencies,
  VerifiedLearningDatasetForTraining,
  VerifiedPairwiseCandidate,
  VerifiedPairwiseCodeManifest,
  VerifiedPairwiseFeatureMatrix,
  VerifiedPairwiseRuntime,
  VerifiedRankingModel,
  VerifyLearningDatasetForTrainingInput,
  VerifyPairwiseCandidateInput,
  VerifyPairwiseFeatureMatrixInput,
} from "./pairwise-logistic.js";
export { predictPairwise, rankEligibleExpressions } from "./rank.js";
export type {
  PairwisePrediction,
  PairwiseRankResult,
  PairwiseRankTieBucket,
  PairwiseRankTieCandidate,
  PairwiseRankTieTrace,
  RankedCandidate,
} from "./rank.js";
export {
  admitTask6Runtime,
  createEvaluationSimulatorVault,
  exportEvaluationSimulatorSnapshot,
  inspectEvaluationAttempt,
  restoreEvaluationSimulatorVault,
  runSealedEvaluation,
  Task6GovernanceError,
  verifySealedTestReplay,
  verifyTask6CodeManifest,
} from "./evaluation.js";
export type {
  CreateEvaluationSimulatorVaultInput,
  CurrentnessCheckEntry,
  DeterministicBaselineProfile,
  EvaluationAttemptState,
  EvaluationAttemptStatus,
  EvaluationFailureEvidence,
  EvaluationMetricResult,
  EvaluationPredicateResult,
  EvaluationRunResult,
  EvaluationRunRequest,
  EvaluationSimulatorSnapshot,
  EvaluationSimulatorVault,
  ProposedBindingScope,
  QualificationDenominatorMember,
  QualificationDenominatorReplay,
  ReviewerIndependenceEntry,
  RiskSliceWitness,
  RestoreEvaluationSimulatorVaultInput,
  SealedTestPairReplay,
  SealedTestReplay,
  SliceMetricResult,
  SimulatedCurrentnessWitness,
  SimulatedReviewerPolicyWitness,
  SimulatorFaultRule,
  SimulatorOperation,
  Task6AuthorityEffect,
  Task6CodeManifest,
  Task6CodeManifestEntry,
  Task6GovernanceErrorCode,
  Task6GovernanceErrorShape,
  Task6RecordMode,
  Task6RuntimeProfile,
  ObservedTask6RuntimeTuple,
  VerifiedTask6Runtime,
  VerifiedTask6CodeManifest,
  VerifiedSealedTestHandle,
  VerifySealedTestReplayInput,
} from "./evaluation.js";
export { derivePairedBootstrapSeed, runPairedGroupBootstrap } from "./bootstrap.js";
export type {
  Binary64Value,
  EvaluationPopulation,
  EvaluationPopulationPair,
  EvaluationSliceDefinition,
  PairedBootstrapInterval,
  PairedBootstrapResult,
  PairedBootstrapSeedInput,
  PairedGroupBootstrapInput,
  SliceBootstrapResult,
  SliceDimension,
  Task6ObjectRef,
} from "./bootstrap.js";
export {
  completeShadowSimulation,
  createShadowEvaluationPlan,
  inspectShadowSimulation,
  observeShadowSimulation,
  startShadowSimulation,
} from "./shadow.js";
export type {
  CompleteShadowSimulationInput,
  CreateShadowEvaluationPlanInput,
  DriftDatasetReplay,
  DriftPairReplay,
  ShadowObservationInput,
  ShadowObservationResponse,
  ShadowOutcomeReplay,
  ShadowRunStatus,
  ShadowRunResult,
  ShadowSimulationHandle,
  StartShadowSimulationInput,
} from "./shadow.js";
export {
  createSimulatedPromotionDecision,
  inspectSimulatedBinding,
  recoverSimulatedBindingReadback,
  simulatePromotionBinding,
} from "./binding.js";
export type {
  CreateSimulatedPromotionDecisionInput,
  RecoverSimulatedBindingReadbackInput,
  SimulatePromotionBindingInput,
  SimulatedBindingProjection,
  SimulatedBindingTransitionResult,
  SimulatedPendingBindingProjection,
  SimulatedPromotionDecision,
  SimulatedVerifiedBindingProjection,
} from "./binding.js";
export {
  evaluateDriftWindow,
  inspectDriftWindow,
  propagateLearningRevocation,
} from "./drift.js";
export type {
  DriftMetricDeltaResult,
  DriftObservation,
  DriftWindowCursor,
  DriftWindowStatus,
  EvaluateDriftWindowInput,
  LearningDriftResult,
  PropagateLearningRevocationInput,
  SimulatedRevocationWitness,
} from "./drift.js";
export { simulateRollback } from "./rollback.js";
export type { RollbackTargetReplay, SimulateRollbackInput } from "./rollback.js";
export {
  consumeBenchmarkAttemptSimulation,
  createBenchmarkAttemptSimulatorRegistry,
  createBenchmarkAttemptSimulatorVault,
  analyzeWritingBenchmarkTaskReview,
  evaluateWritingBenchmarkQualityGate,
  inspectBenchmarkAttemptSimulation,
  interruptBenchmarkAttemptSimulation,
  meanOriginalReviewEditEffort,
  normalizedWritingBenchmarkEditDistance,
  resumeBenchmarkAttemptSimulation,
  runWritingBenchmarkHierarchicalBootstrap,
  sealBenchmarkAttemptSimulation,
  selectBenchmarkCandidate,
  verifyBenchmarkAttemptDraft,
  verifyBenchmarkCandidateControls,
  verifyWritingBenchmarkManifest,
  WritingBenchmarkError,
} from "./writing-benchmark.js";
export type {
  BenchmarkAttemptSimulationState,
  BenchmarkAttemptSimulatorRegistry,
  BenchmarkAttemptSimulatorVault,
  AnalyzeWritingBenchmarkTaskReviewInput,
  EvaluateWritingBenchmarkQualityGateInput,
  BenchmarkCandidateChain,
  BenchmarkCandidateEvaluation,
  BenchmarkCandidateSelection,
  BenchmarkGenerationControl,
  BenchmarkTieBreakTrace,
  NormalizedWritingBenchmarkEditDistance,
  NormalizedWritingBenchmarkEditDistanceInput,
  MeanOriginalReviewEditEffortInput,
  OriginalReviewEditDistance,
  RunWritingBenchmarkHierarchicalBootstrapInput,
  SelectBenchmarkCandidateInput,
  VerifiedBenchmarkAttemptDraft,
  VerifiedBenchmarkCandidateControls,
  VerifiedWritingBenchmarkManifest,
  VerifyBenchmarkCandidateControlsInput,
  VerifyBenchmarkAttemptDraftInput,
  VerifyWritingBenchmarkManifestInput,
  WritingBenchmarkBinary64,
  WritingBenchmarkErrorCode,
  WritingBenchmarkHierarchicalBootstrapResult,
  WritingBenchmarkBootstrapSeedMaterial,
  WritingBenchmarkMetricPair,
  WritingBenchmarkInterval,
  WritingBenchmarkQualityGateResult,
  WritingBenchmarkReviewObservation,
  WritingBenchmarkTaskReviewResult,
  WritingBenchmarkTrainingPartition,
} from "./writing-benchmark.js";
export * from "./promotion.js";
export * from "./records.js";
